services:
  postgres:
    container_name: pgvector-search-demo
    image: pgvector/pgvector:pg17
    ports:
      - "5433:5432"
    volumes:
      - pgvector-search-demo:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - DEBUG=true

volumes:
  pgvector-search-demo:
